name: Deploy resume assistant to staging environment    

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        environment: STAGING

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
                
            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.SSH_KEY }}

            - name: Deploy docker compose
              env:
                HOST: ${{ vars.HOST }}
              run: |
                  ssh admin@$HOST -o StrictHostKeyChecking=no "cd /home/admin/resume-assistant && ssh-agent bash -c 'ssh-add ~/.ssh/id_ed25519; git pull origin' && sudo docker compose down && sudo docker compose up --build -d"